-- This file is for storing functions and stuff that is useful.

--[[
perfect move for HUDs?: {"move_left_right_using_parameter", 0, GetScale()}

get_base_data():
	getAngleOfAttack()
	getAngleOfSlide()
	getBarometricAltitude()
	getCanopyPos()
	getCanopyState()
	getEngineLeftFuelConsumption()
	getEngineLeftRPM()
	getEngineLeftTemperatureBeforeTurbine()
	getEngineRightFuelConsumption()
	getEngineRightRPM()
	getEngineRightTemperatureBeforeTurbine()
	getFlapsPos()
	getFlapsRetracted()
	getHeading()
	getHorizontalAcceleration()
	getIndicatedAirSpeed()
	getLandingGearHandlePos()
	getLateralAcceleration()
	getLeftMainLandingGearDown()
	getLeftMainLandingGearUp()
	getMachNumber()
	getMagneticHeading()
	getNoseLandingGearDown()
	getNoseLandingGearUp()
	getPitch()
	getRadarAltitude()
	getRateOfPitch()
	getRateOfRoll()
	getRateOfYaw()
	getRightMainLandingGearDown()
	getRightMainLandingGearUp()
	getRoll()
	getRudderPosition()
	getSpeedBrakePos()
	getSelfAirspeed()
	getSelfCoordinates()
	getSelfVelocity()
	getStickPitchPosition()
	getStickRollPosition()
	getThrottleLeftPosition()
	getThrottleRightPosition()
	getTotalFuelWeight()
	getTrueAirSpeed()
	getVerticalAcceleration()
	getVerticalVelocity()
	getWOW_LeftMainLandingGear()
	getWOW_NoseLandingGear()
	getWOW_RightMainLandingGear()

--]]