start_custom_command   = 10000
local __count_custom = start_custom_command - 1
--- Increments a custom command counter and returns the new value.
--- @return integer
local function __custom_counter()
	__count_custom = __count_custom + 1
	return __count_custom
end

keys =
{
	-- ==== Weapon systems ==== 					

	manual_bay_operation     				= __custom_counter(),		-- 10000
	weap_bay_select							= __custom_counter(),
	pickle_on								= __custom_counter(),
	pickle_off								= __custom_counter(),
	first_stage_trigger_on					= __custom_counter(),
	first_stage_trigger_off					= __custom_counter(),
	second_stage_trigger_on					= __custom_counter(),
	second_stage_trigger_off				= __custom_counter(),
	countermeasuresDispense                 = __custom_counter(),
	countermeasuresDispenseOff              = __custom_counter(),

	-- ==== Side Panel ==== 

	air_brake								= __custom_counter(),		--10010
	airBrakeOn								= __custom_counter(),
	airBrakeOff								= __custom_counter(),
	FLCSTest								= __custom_counter(),
	GearUp					                = __custom_counter(),
	GearDown                                = __custom_counter(),
	formation_lights						= __custom_counter(),
	form_on									= __custom_counter(),
	form_off								= __custom_counter(),
	position_on								= __custom_counter(),
	position_off							= __custom_counter(),		--10020
	beacon_lights							= __custom_counter(),
	back_lights								= __custom_counter(),
	flood_lights							= __custom_counter(),	
	console_brightness 						= __custom_counter(),
	inst_brightness							= __custom_counter(),
	display_brightness						= __custom_counter(),
	flood_brightness						= __custom_counter(),
	mode_selector							= __custom_counter(),
	position_selector						= __custom_counter(),
	form_brightness							= __custom_counter(),		--10030
	MTR_selector							= __custom_counter(),
	motor_selector							= __custom_counter(),
	engine_selector							= __custom_counter(),
	tanks_selector							= __custom_counter(),
	aar_light_brightness					= __custom_counter(),
	aar_door_selector						= __custom_counter(),
	FLCS_cover_selector						= __custom_counter(),
	FLCS_selector							= __custom_counter(),
	CAN_JET_selector						= __custom_counter(),
	con_bright_on							= __custom_counter(),		--10050
	con_bright_off							= __custom_counter(),

	-- ==== Instrument Panel ====

	master_arm_switch						= __custom_counter(),
	LDG_light_selector						= __custom_counter(),
	PTJ_selector							= __custom_counter(),
	BAT_Selector							= __custom_counter(),
	batToggle									= __custom_counter(),
	bat_off									= __custom_counter(),
	taxi_on									= __custom_counter(),
	landing_on								= __custom_counter(),
	land_taxi_off							= __custom_counter(),
	APU										= __custom_counter(),		--10060
	l_engine_start							= __custom_counter(),
	l_engine_stop							= __custom_counter(),
	r_engine_start							= __custom_counter(),
	r_engine_stop							= __custom_counter(),
	nws_rate								= __custom_counter(),

	
	-------------------------------------------------------
	--FC3 Commands
	-------------------------------------------------------
	ICommandHUDBrightnessDown	            = 747,
	ICommandHUDBrightnessUp	            	= 746,
	PlaneGear								= 68,
	PlaneFonar								= 71,
	PlaneSalvoOnOff							= 81,
	PlaneChangeWeapon						= 101,
	PlaneChangeWaypoint						= 102,
	PlaneZoomIn								= 103,
	PlaneZoomOut							= 104,
	PlaneBrightnessILS						= 156,
	PlaneLightsOnOff						= 175,
	PlaneDropSnarOnce						= 176,
	PlaneHeadLightOnOff						= 328,
	PlaneModeNAV							= 105,
	PlaneModeBVR							= 106,
	PlaneModeVS								= 107,
	PlaneModeBore							= 108,
	PlaneModeHelmet							= 109,
	PlaneModeFI0							= 110,
	PlaneModeGround							= 111,
	SwitchMasterArm							= 283,
	PlanePickleOn							= 350,
	PlanePickleOff							= 351,
	PlaneWheelBrakeLeftOn					= 961,
	PlaneWheelBrakeLeftOff					= 962,
	PlaneWheelBrakeRightOn	 				= 963,
	PlaneWheelBrakeRightOff					= 964,	
	PlaneMasterCautionOff					= 379,
	PlaneGearUp								= 430,
	PlaneGearDown							= 431,
	PlaneDropSnarOnceOff					= 536,
	PlaneMasterCaution						= 252,
	PlaneScalesReject						= 253,
	PlaneBettyRepeat						= 254,
	ChangeGunRateOfFire						= 280,
	ChangeRippleQuantity					= 281,
	ChangeRippleInterval					= 282,
	ChangeReleaseMode						= 284,
	ChangeRippleIntervalDown				= 308,
	PlaneLaunchPermissionOverride			= 349,
	PlaneCMDDispence						= 364,
	PlaneCMDDispenceOff						= 365,
	PlaneCMDDispenceStop					= 366,
	PlaneCMDDispenceStopOff					= 367,
	PlaneCMDChangeRippleQuantity			= 368,
	PlaneCMDChangeRippleQuantityOff 		= 369,
	PlaneCMDChangeRippleInterval			= 370,
	PlaneCMDChangeRippleIntervalOff 		= 371,
	PlaneCMDChangeBurstAmount				= 372,
	PlaneCMDChangeBurstAmountOff			= 373,
	PlaneCMDCancelCurrentProgram			= 374,
	PlaneCMDCancelCurrentProgramOff 		= 375,
	PlaneCMDChangeBoard						= 376,
	PlaneCMDShowAmountOrProgram				= 377,
	PlaneLaserRangerOnOff					= 392,
	PlaneNightVisionGogglesOnOff			= 438,
	HOTAS_CoolieUp	 						= 539,
	HOTAS_CoolieDown 						= 540,
	HOTAS_CoolieLeft 						= 541,
	HOTAS_CoolieRight						= 542,
	HOTAS_CoolieOff  						= 543,
	HOTAS_TargetManagementSwitchUp	  		= 544,
	HOTAS_TargetManagementSwitchDown  		= 545,
	HOTAS_TargetManagementSwitchLeft  		= 546,
	HOTAS_TargetManagementSwitchRight 		= 547,
	HOTAS_TargetManagementSwitchOff   		= 548,
	HOTAS_DataManagementSwitchUp   			= 549,
	HOTAS_DataManagementSwitchDown 			= 550,
	HOTAS_DataManagementSwitchLeft 			= 551,
	HOTAS_DataManagementSwitchRight			= 552,
	HOTAS_DataManagementSwitchOff  			= 553,
	--from iCommand.h
	PlaneSAUAutomatic 						= 58,			
	PlaneSAUHBarometric 					= 59,			
	PlaneSAUHRadio 							= 60,			
	PlaneSAUHorizon							= 61,			
	PlaneAutopilot 							= 62, 
	PlaneAUTOnOff 							= 63,			
	PlaneAUTIncrease 						= 64,			
	PlaneAUTDecrease						= 65,			
	PlaneGear 								= 68,			
	PlaneHook 								= 69,			
	PlanePackWing 							= 70,			
	PlaneFonar 								= 71,			
	PlaneFlaps 								= 72,			
	planeAirBrake 							= 73,			
	PlaneWheelBrakeOn 						= 74,			
	PlaneWheelBrakeOff 						= 75,			
	PlaneParachute 							= 76,			
	PlaneDropSnar 							= 77,			
	PlaneWingtipSmokeOnOff 					= 78,			
	PlaneFuelOn 							= 79,			
	PlaneFuelOff							= 80,			
	PlaneSalvoOnOff 						= 81,			
	PiCommandSelecterUplaneJettisonWeapons 	= 82,			
	PlaneEject 								= 83,		
	PlaneFire 								= 84,			
	PlaneFireOff 							= 85,			
	PlaneRadarOnOff 						= 86,			
	PlaneEOSOnOff 							= 87,			
	PlaneRadarLeft 							= 88,			
	PlaneRadarRight 						= 89,			
	PlaneRadarUp							= 90,			
	PlaneRadarDown 							= 91,			
	PlaneRadarCenter 						= 92,			
	PlaneTrimLeft							= 93,			
	PlaneTrimRight 							= 94,			
	PlaneTrimUp 							= 95,			
	PlaneTrimDown 							= 96,			
	PlaneTrimCancel 						= 97,			
	PlaneTrimLeftRudder						= 98,			
	PlaneTrimRightRudder 					= 99,			
	PlaneChangeLock 						= 100,			
	PlaneChangeWeapon 						= 101,			
	PlaneChangeTarget 						= 102,			
	PlaneZoomIn 							= 103,			
	PlaneZoomOut 							= 104,			
	PlaneModeNAV 							= 105,			
	PlaneModeBVR 							= 106,			
	PlaneModeVS 							= 107,			
	PlaneModeBore 							= 108,			
	PlaneModeHelmet 						= 109,			
	PlaneModeFI0 							= 110,			
	PlaneModeGround 						= 111,			
	PlaneModeGrid 							= 112,			
	PlaneModeCannon 						= 113,			
	PlaneDoAndHome 							= 114,			
	PlaneDoAndBack 							= 115,			
	PlaneFormation 							= 116,			
	PlaneJoinUp    							= 117,			
	PlaneAttackMyTarget 					= 118,			
	PlaneCoverMySix 						= 119,			
	PlaneShipTakeOff 						= 120,			
	ActiveJamming 							= 136,
	LandDetailsIncrease 					= 137,			
	LandDetailsDecrease 					= 138,			
	SelecterLeft							= 139,			
	SelecterRight 							= 140,			
	SelecterUp  							= 141,			
	SelecterDown 							= 142,			
	RefusalTWS 								= 143,			
	PlaneResetMasterWarning 				= 144,
	PlaneFlapsOn 							= 145,
	PlaneFlapsOff 							= 146,
	planeAirBrakeOn 						= 147,
	planeAirBrakeOff 						= 148,
	PlaneAirRefuel 							= 155,			
	BrightnessILS 							= 156,			
	PlaneAUTIncreaseLeft 					= 161,
	PlaneAUTDecreaseLeft 					= 162,
	PlaneAUTIncreaseRight 					= 163,
	PlaneAUTDecreaseRight 					= 164,
	PlaneLightsOnOff 						= 175,		
	PlaneDropSnarOnce 						= 176,		
	PlaneJettisonFuelTanks 					= 178,		
	PlaneWingmenCommand 					= 179,		
	PlaneDown 								= 186,		
	PlaneUp 								= 187,
	PlaneLeft 								= 188,
	PlaneRight 								= 189,
	PlaneUpStart 							= 193,
	PlaneUpStop 							= 194,
	PlaneDownStart							= 195,
	PlaneDownStop 							= 196,
	PlaneLeftStart 							= 197,
	PlaneLeftStop 							= 198,
	PlaneRightStart 						= 199,
	PlaneRightStop 							= 200,
	PlaneLeftRudderStart 					= 201,
	PlaneLeftRudderStop 					= 202,
	PlaneRightRudderStart 					= 203,
	PlaneRightRudderStop 					= 204,
	PlaneTrimStop 							= 215,
	SelecterUpRight 						= 226,
	SelecterDownRight 						= 227,
	SelecterDownLeft 						= 228,
	SelecterUpLeft 							= 229,
	SelecterStop 							= 230,
	PlaneRadarUpRight 						= 231,
	PlaneRadarDownRight 					= 232,
	PlaneRadarDownLeft 						= 233,
	PlaneRadarUpLeft 						= 234,
	PlaneRadarStop 							= 235,
	PlaneHUDFilterOnOff 					= 247,			
	PlaneMasterCaution 						= 252,			
	PlaneScalesReject						= 253,			
	PlaneBettyRepeat 						= 254,			
	ThreatMissilePadlock 					= 258,
	AllMissilePadlock 						= 259,
	DecreaseRadarScanArea 					= 262,
	IncreaseRadarScanArea 					= 263,
	AWACSHomeBearing 						= 267,
	AWACSTankerBearing 						= 268,
	AWACSBanditBearing 						= 269,
	AWACSDeclare 							= 270,
	EasyRadarOnOff 							= 271,
	AutoLockOnNearestAircraft 				= 272,
	AutoLockOnCenterAircraft 				= 273,
	AutoLockOnNextAircraft 					= 274,
	AutoLockOnPreviousAircraft 				= 275,
	AutoLockOnNearestSurfaceTarget 			= 276,
	AutoLockOnCenterSurfaceTarget 			= 277,
	AutoLockOnNextSurfaceTarget 			= 278,
	AutoLockOnPreviousSurfaceTarget 		= 279,
	ChangeGunRateOfFire 					= 280,
	ChangeRippleQuantity 					= 281,
	ChangeRippleInterval 					= 282,
	SwitchMasterArm 						= 283,
	ChangeReleaseMode 						= 284,
	PlaneRadarChangeMode 					= 285,
	ChangeRWRMode 							= 286,
	FlightClockReset 						= 288,
	PlaneCockpitIllumination 				= 300,
	ChangeRippleIntervalDown 				= 308,	
	EnginesStart 							= 309,	
	EnginesStop 							= 310,	
	LeftEngineStart 						= 311,	
	RightEngineStart 						= 312,	
	LeftEngineStop							= 313,	
	RightEngineStop 						= 314,	
	PowerOnOff 								= 315,	
	PowerGeneratorLeft 						= 711,
	PowerGeneratorRight 					= 712,
	BatteryPower 							= 1073,  
	AltimeterPressureIncrease 				= 316,	
	AltimeterPressureDecrease 				= 317,	
	AltimeterPressureStop 					= 318,
	PlaneHeadLightOnOff 					= 328,	
	PlaneLockPadlock 						= 329,	
	PlaneUnlockPadlock 						= 330,	
	PlaneLaunchPermissionOverride			= 349,	
	PlanePickleOn 							= 350,	
	PlanePickleOff 							= 351,
	PlaneDropFlareOnce 						= 357,	
	PlaneDropChaffOnce 						= 358,	
	PlaneCMDDispence 						= 364,	
	PlaneCMDDispenceOff 					= 365,
	PlaneCMDDispenceStop 					= 366,	
	PlaneCMDDispenceStopOff 				= 367,
	PlaneCMDChangeRippleQuantity 			= 368,	
	PlaneCMDChangeRippleInterval 			= 370,	
	PlaneCMDChangeBurstAmount 				= 372,	
	PlaneCMDChangeBurstAmountOff 			= 373,
	PlaneCMDCancelCurrentProgram 			= 374,	
	PlaneCMDChangeBoard 					= 376,	
	PlaneCMDShowAmountOrProgram 			= 377,	
	PlaneCancelWeaponsDelivery 				= 378,	
	PlaneMasterCautionOff 					= 379,
	PlaneStabTangBank 						= 386,	
	PlaneStabHbarBank 						= 387,	
	PlaneStabHorizon 						= 388,	
	PlaneStabHbar 							= 389,	
	PlaneStabHrad 							= 390,	
	ActiveIRJamming 						= 391,	
	PlaneLaserRangerOnOff 					= 392, 	
	PlaneNightTVOnOff						= 393,   
	PlaneChangeRadarPRF 					= 394,   
	PlaneStabCancel 						= 408,	
	PlaneThreatWarnSoundVolumeDown 			= 409,	
	PlaneThreatWarnSoundVolumeUp 			= 410,	
	ViewLaserOnOff 							= 411,
	PlaneIncreaseBase_Distance 				= 412,     
	PlaneDecreaseBase_Distance				= 413,     
	PlaneStopBase_Distance 					= 414,
	PlaneAutopilotOverrideOn 				= 427,
	PlaneAutopilotOverrideOff 				= 428,
	PlaneRouteAutopilot 					= 429,
	PlaneGearUp 							= 430,
	PlaneGearDown 							= 431,
	ViewNightVisionGogglesOn 				= 438,
	PlaneDesignate_CageOn 					= 439,
	PlaneDesignate_CageOff 					= 440,
	PlaneDesignate_CageOn_vertical 			= 441,
	PlaneDesignate_CageOn_horizontal 		= 442,
	PlaneDLK_Target1 						= 443,
	PlaneDLK_Target2 						= 444,
	PlaneDLK_Target3 						= 445,
	PlaneDLK_RefPoint 						= 446,
	PlaneDLK_Wingman1 						= 447,
	PlaneDLK_Wingman2 						= 448,
	PlaneDLK_Wingman3 						= 449,
	PlaneDLK_Wingman4 						= 450,
	PlaneDLK_All 							= 451,
	PlaneDLK_Erase 							= 452,
	PlaneDLK_Ingress 						= 453,
	PlaneDLK_SendMemory 					= 454,
	PlaneNavChangePanelModeRight 			= 455,
	PlaneNavChangePanelModeLeft 			= 456,
	PlaneNavSetFixtakingMode 				= 457,
	PlaneNav_DLK_OnOff 						= 458,
	PlaneNav_PB1 							= 459,
	PlaneNav_PB2 							= 460,
	PlaneNav_PB3 							= 461,
	PlaneNav_PB4 							= 462,
	PlaneNav_PB5 							= 463,
	PlaneNav_PB6 							= 464,
	PlaneNav_PB7 							= 465,
	PlaneNav_PB8 							= 466,
	PlaneNav_PB9 							= 467,
	PlaneNav_PB0 							= 468,
	PlaneNav_Steerpoints 					= 469,
	PlaneNav_INU_realign 					= 470,
	PlaneNav_POS_corrMode 					= 471,
	PlaneNav_INU_precise_align 				= 472,
	PlaneNav_Airfields 						= 473,
	PlaneNav_INU_normal_align  				= 474,
	PlaneNav_Targets 						= 475,
	PlaneNav_Enter 							= 476,
	PlaneNav_Cancel 						= 477,
	PlaneNav_POS_init 						= 478,
	PlaneNav_SelfCoord 						= 479,
	PlaneNav_CourseTimeRange 				= 480,
	PlaneNav_Wind 							= 481,
	PlaneNav_THeadingTimeRangeF 			= 482,
	PlaneNav_BearingRangeT 					= 483,
	PlaneCockpitIlluminationPanels 			= 493,
	PlaneCockpitIlluminationGauges 			= 494,
	Plane_RouteMode 						= 506,
	Plane_DescentMode 						= 507,
	Plane_DescentModeOff 					= 508,
	Plane_SpotLight_left 					= 511,
	Plane_SpotLight_right 					= 512,
	Plane_SpotLight_up						= 513,
	Plane_SpotLight_down 					= 514,
	Plane_SpotLight_stop 					= 515,
	PlaneRotorTipLights 					= 516,
	Plane_SpotSelect_switch 				= 517,
	PlaneAntiCollisionLights 				= 518,
	PlaneNavLights_CodeModeOn 				= 519,
	PlaneNavLights_CodeModeOff				= 520,
	PlaneFormationLights 					= 521,
	Plane_EngageAirDefenses 				= 522,
	Plane_EngageGroundTargets				= 523,
	Plane_AutomaticTracking_Gunsight_switch = 524,
	Plane_AutomaticTurn 					= 526,
	Plane_GroundMovingTarget 				= 527,
	Plane_AirborneTarget 					= 528,
	Plane_HeadOnAspect 						= 529,
	Plane_ChangeDeliveryMode_right 			= 530,
	Plane_ChangeDeliveryMode_left 			= 531,
	Plane_WeaponMode_Manual_Auto 			= 532,
	Plane_WeaponMode_switch 				= 533,
	Plane_AmmoTypeSelect 					= 534,
	Plane_FireRate 							= 535,
	PlaneDropSnarOnceOff 					= 536,
	HelicopterHover 						= 537,
	AutopilotEmergOFF 						= 538,
	Plane_HOTAS_CoolieUp 					= 539,
	Plane_HOTAS_CoolieDown 					= 540,
	Plane_HOTAS_CoolieLeft 					= 541,
	Plane_HOTAS_CoolieRight 				= 542,
	Plane_HOTAS_CoolieOff 					= 543,
	Plane_HOTAS_TargetManagementSwitchUp 	= 544,
	Plane_HOTAS_TargetManagementSwitchDown 	= 545,
	Plane_HOTAS_TargetManagementSwitchLeft 	= 546,
	Plane_HOTAS_TargetManagementSwitchRight = 547,
	Plane_HOTAS_TargetManagementSwitchOff 	= 548,
	Plane_HOTAS_DataManagementSwitchUp 		= 549,
	Plane_HOTAS_DataManagementSwitchDown 	= 550,
	Plane_HOTAS_DataManagementSwitchLeft 	= 551,
	Plane_HOTAS_DataManagementSwitchRight 	= 552,
	Plane_HOTAS_DataManagementSwitchOff		= 553,
	Plane_HOTAS_TriggerSecondStage 			= 554,
	Plane_HOTAS_TriggerFirstStage 			= 555,
	Plane_HOTAS_CMS_Up 						= 556,
	Plane_HOTAS_CMS_Down 					= 557,
	Plane_HOTAS_CMS_Left 					= 558,
	Plane_HOTAS_CMS_Right 					= 559,
	Plane_HOTAS_CMS_Off 					= 560,
	Plane_HOTAS_MasterModeControlButton 	= 561,
	Plane_HOTAS_NoseWheelSteeringButton 	= 562,
	Plane_HOTAS_NoseWheelSteeringButtonOff 	= 606,
	Plane_HOTAS_BoatSwitchForward 			= 563,
	Plane_HOTAS_BoatSwitchAft 				= 564,
	Plane_HOTAS_BoatSwitchCenter 			= 565,
	Plane_HOTAS_ChinaHatForward 			= 566,
	Plane_HOTAS_ChinaHatAft 				= 567,
	Plane_HOTAS_ChinaHatOff 				= 589,
	Plane_HOTAS_PinkySwitchForward 			= 568,
	Plane_HOTAS_PinkySwitchAft 				= 569,
	Plane_HOTAS_PinkySwitchCenter 			= 570,
	Plane_HOTAS_LeftThrottleButton 			= 571,
	Plane_HOTAS_MIC_SwitchUp 				= 572,
	Plane_HOTAS_MIC_SwitchDown 				= 573,
	Plane_HOTAS_MIC_SwitchLeft 				= 574,
	Plane_HOTAS_MIC_SwitchRight 			= 575,
	Plane_HOTAS_MIC_SwitchOff 				= 576,
	Plane_HOTAS_SpeedBrakeSwitchForward 	= 577,
	Plane_HOTAS_SpeedBrakeSwitchAft 		= 578,
	Plane_HOTAS_SpeedBrakeSwitchCenter 		= 579,
	Plane_HOTAS_MasterModeControlButtonUP 	= 633,
	Plane_HOTAS_TDC_depress_on  			= 634,
	Plane_HOTAS_TDC_depress_off 			= 635,
	Plane_HOTAS_TriggerSecondStage_Off 		= 638,
	Plane_HOTAS_TriggerFirstStage_Off  		= 639,
	Plane_HOTAS_CMS_Zaxis 					= 1041,
	Plane_HOTAS_CMS_Zaxis_Off 				= 1042,
	Plane_HOTAS_BoatSwitchOff				= 822,
	Plane_HOTAS_BoatSwitchForwardMomentary 	= 823,
	Plane_HOTAS_BoatSwitchAftMomentary 		= 824,
	Plane_CockpitShowPilotOnOff				= 835,
	Plane_HOTAS_LeftThrottleButton_Off 		= 1557,
	PlaneRadarHorizontal 	   				= 2025,
	PlaneRadarVertical 		   				= 2026,
	PlaneRadarHorizontalAbs    				= 2027,
	PlaneRadarVerticalAbs 	   				= 2028,
	PlaneMFDZoom 		       				= 2029,
	PlaneMFDZoomAbs			   				= 2030,
	PlaneSelecterHorizontal    				= 2031,
	PlaneSelecterVertical 	   				= 2032,
	PlaneSelecterHorizontalAbs 				= 2033,
	PlaneSelecterVerticalAbs   				= 2034,
	PlaneBase_Distance 		   				= 2040,
	PlaneBase_DistanceAbs 	   				= 2041,
	LampsControl							= 762,
	LampsControl_up							= 800,

	-- Analog commands
	PlaneRadarHorizontal 	   = 2025,
	PlaneRadarVertical 		   = 2026,
	PlaneRadarHorizontalAbs    = 2027,
	PlaneRadarVerticalAbs 	   = 2028,
	PlaneMFDZoom 		       = 2029,
	PlaneMFDZoomAbs			   = 2030,
	PlaneSelecterHorizontal    = 2031,
	PlaneSelecterVertical 	   = 2032,
	PlaneSelecterHorizontalAbs = 2033,
	PlaneSelecterVerticalAbs   = 2034,
	PlaneBase_Distance 		   = 2040,
	PlaneBase_DistanceAbs 	   = 2041,
	
		
	
	LampsControl							= 762,
	LampsControl_up							= 800,
}


deviceCommands =
{	
	BrakesON      							= 10138,
	BrakesOFF     							= 10139,
	L_BRAKE       							= 10156,
	R_BRAKE       							= 10157,
	B_BRAKE       							= 10158,
	--Brakes        						= 10123,
	P_BRAKE	   							= 10159,
	YAW_AXIS								= 10163,
	ROLL_INPUT								= 10164,
	PITCH_INPUT							= 10165,
	
	
	
	
}


start_command   = 3100
local __count = start_command - 1
--- Increments a command counter and returns the new value.
--- @return integer
local function __counter()
	__count = __count + 1
	return __count
end

deviceCommands =
{
	-- ==== Left Side Panel ====

	Console_Brightness						= __counter(),
	INST_Brightness							= __counter(),
	DISPLAY_Brightness						= __counter(),
	FLOOD_Brightness						= __counter(),
	MODE_Selector							= __counter(),
	POSTITION_Selector						= __counter(),
	BEACON_Selector							= __counter(),
	FORM_Brightness							= __counter(),
	MTR_Selector							= __counter(),
	MOTOR_Selector							= __counter(),
	ENGINE_Selector							= __counter(),
	TANKS_Selector							= __counter(),
	AAR_LIGHT_Brightness					= __counter(),
	AAR_DOOR_Selector						= __counter(),
	FLCS_COVER_Selector						= __counter(),
	FLCS_Selector							= __counter(),
	CAN_JET_Selector						= __counter(),	

	-- ==== Instrument Panel ====
	gear_lever							= __counter(),
	LDG_LIGHT_Selector						= __counter(),
	PTJ_Selector							= __counter(),
	batSwitch								= __counter(),
	arm_switch								= __counter(),
	KB_1									= __counter(),
	KB_2									= __counter(),
	KB_3									= __counter(),
	KB_4									= __counter(),
	KB_5									= __counter(),
	KB_6									= __counter(),
	KB_7									= __counter(),
	KB_8									= __counter(),
	KB_9									= __counter(),
	KB_10									= __counter(),
	KB_11									= __counter(),
	KB_12									= __counter(),
	KB_13									= __counter(),
	KB_14									= __counter(),
	KB_15									= __counter(),
	KB_16									= __counter(),
	KB_17									= __counter(),
	KB_18									= __counter(),
	KB_19									= __counter(),
	KB_20									= __counter(),
	KB_21									= __counter(),
	KB_22									= __counter(),
	day_night_switch						= __counter(),
	r1_vol_knob								= __counter(),
	r2_vol_knob								= __counter(),
	r3_vol_knob								= __counter(),
	r4_vol_knob								= __counter(),
	hud_bright								= __counter(),

	-- ==== Left MFD ====

	l_osb_1									= __counter(),
	l_osb_2									= __counter(),
	l_osb_3									= __counter(),
	l_osb_4									= __counter(),
	l_osb_5									= __counter(),
	l_osb_6									= __counter(),
	l_osb_7									= __counter(),
	l_osb_8									= __counter(),
	l_osb_9									= __counter(),
	l_osb_10								= __counter(),
	l_osb_11								= __counter(),
	l_osb_12								= __counter(),
	l_osb_13								= __counter(),
	l_osb_14								= __counter(),
	l_osb_15								= __counter(),
	l_osb_16								= __counter(),	
	l_osb_17								= __counter(),
	l_osb_18								= __counter(),

	-- ==== Primary MFD ====

	P_osb_1									= __counter(),
	P_osb_2									= __counter(),
	P_osb_3									= __counter(),
	P_osb_4									= __counter(),
	P_osb_5									= __counter(),
	P_osb_6									= __counter(),
	P_osb_7									= __counter(),
	P_osb_8									= __counter(),
	P_osb_9									= __counter(),
	P_osb_10								= __counter(),
	P_osb_11								= __counter(),
	P_osb_12								= __counter(),
	P_osb_13								= __counter(),
	P_osb_14								= __counter(),
	P_osb_15								= __counter(),
	P_osb_16								= __counter(),	
	P_osb_17								= __counter(),
	P_osb_18								= __counter(),
	P_osb_19								= __counter(),
	P_osb_20								= __counter(),

	-- ==== Right MFD ====

	R_osb_1									= __counter(),
	R_osb_2									= __counter(),
	R_osb_3									= __counter(),
	R_osb_4									= __counter(),
	R_osb_5									= __counter(),
	R_osb_6									= __counter(),
	R_osb_7									= __counter(),
	R_osb_8									= __counter(),
	R_osb_9									= __counter(),
	R_osb_10								= __counter(),
	R_osb_11								= __counter(),
	R_osb_12								= __counter(),
	R_osb_13								= __counter(),
	R_osb_14								= __counter(),
	R_osb_15								= __counter(),
	R_osb_16								= __counter(),	
	R_osb_17								= __counter(),
	R_osb_18								= __counter(),

	-- ==== Left UFD ====

	L_ufd_1									= __counter(),
	L_ufd_2									= __counter(),
	L_ufd_3									= __counter(),

	-- ==== Right UFD ====

	R_ufd_1									= __counter(),
	R_ufd_2									= __counter(),
	R_ufd_3									= __counter(),

	-- ==== UFC Controller ====

	U_osb_1									= __counter(),
	U_osb_2									= __counter(),
	U_osb_3									= __counter(),
	U_osb_4									= __counter(),
	U_osb_5									= __counter(),
	U_osb_6									= __counter(),
	U_osb_7									= __counter(),
	U_osb_8									= __counter(),
	U_osb_9									= __counter(),
	U_osb_10								= __counter(),
	U_aa									= __counter(),
	U_ag									= __counter(),
	U_nav									= __counter(),
	U_inst									= __counter(),

	-- ==== Right Side Panel ====

	APU_switch								= __counter(),
	LGenSwitch							= __counter(),
	RGenSwitch							= __counter(),
	ParkingBrake							= __counter(),
	L_aux_vol								= __counter(),
	R_aux_vol  								= __counter(),
	aux_mode								= __counter(),
	aux_brt									= __counter(),
	aux_vox									= __counter(),
	aux_rcn									= __counter(),
	aux_aux									= __counter(),
	O2 										= __counter(),
	OBOGS 									= __counter(),
	ecs_temp								= __counter(),
	ecs_flow								= __counter(),
	ecs_aut_man								= __counter(),
	ecs_rate								= __counter(),
	




}

--[[start_command   = 3000
deviceCommands =
{	
	 BrakesON      							= 10038,
	 BrakesOFF     							= 10039,
	 L_BRAKE       							= 10056,
	 R_BRAKE       							= 10057,
	 B_BRAKE       							= 10058,
	 --Brakes        						= 10023,
	 P_BRAKE	   							= 10059,
}]]